### ISSUE TITLE
tarball release (distro-agnostic)

### ISSUE THREAD

**Issue by baimafeima** [craigcabrey/luminance#24]
Could you offer a versioned tarball release? I think this would be a better choice than offering a distro specific package such as RPM or DEB packages.

**Comment by probonopd** [comment]
...or consider an [AppImage](http://appimage.org/), maybe.app

**Comment by craigcabrey** [comment]
tagged v0.1.0 and uploaded a tarball that follows the usual configure, make, make install flow.

**Comment by baimafeima** [comment]
Great! Thanks a lot.
